// Per-point and per-sample racing-line data.
//
// Responsibility: the data contract between the racing-line spline and
// everything that reads it.
// Single reason to change: a new per-point authored or generated field is
// needed.
//
// Two structs, deliberately: FRacingLinePoint is authored/generated data
// stored once per spline key on AMidanRacingLineSpline. FRacingLineSample is
// the interpolated result at an arbitrary arc length, which is what the
// follower and the opponent controller actually consume — a spline has a
// handful of keys, but a car needs a value at wherever it currently is.

#pragma once

#include "CoreMinimal.h"
#include "MidanRacingLineData.generated.h"

/**
 * One authored/generated racing-line point, index-aligned with the owning
 * AMidanRacingLineSpline's spline component keys.
 */
USTRUCT(BlueprintType)
struct MIDANAI_API FRacingLinePoint
{
	GENERATED_BODY()

	/**
	 * Reference target speed at this point, km/h, generated by
	 * MidanSpeedProfileGenerator against a reference grip coefficient of 1.0.
	 *
	 * Not the final speed any given AI drives at — AMidanOpponentController
	 * scales this per-difficulty at runtime (TargetSpeedMultiplier, and
	 * TyreFrictionMultiplier on the sqrt-scaled cornering portion) rather
	 * than the racing line holding one profile per difficulty tier. See
	 * docs/ASSUMPTIONS.md for why: recomputing per-tier would mean N stored
	 * profiles for N difficulty tiers, all derived from the same curvature
	 * data, for a runtime cost (two multiplies) that is definitely not worth
	 * spending storage and generation time to avoid.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RacingLine")
	float ReferenceTargetSpeedKmh = 0.f;

	/**
	 * True when ReferenceTargetSpeedKmh here is lower than the pure cornering
	 * grip limit would allow — i.e. the backward braking pass reduced it.
	 * Marks where TyreFrictionMultiplier's sqrt-scaling applies and where
	 * MidanMistakeModel's late-brake mistake can trigger.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RacingLine")
	bool bBrakingZone = false;

	/** Lateral offset bounds from the racing line centre, cm, signed positive
	 *  right of the direction of travel — same convention as
	 *  FMidanTrackPosition::LateralOffset in MidanCore. Hand-authored: how far
	 *  UMidanOvertakeComponent and UMidanAvoidanceComponent may push a car off
	 *  the racing line before it would run out of track or clip another car's
	 *  line through a blind apex. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RacingLine")
	float LateralOffsetMinCm = -300.f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RacingLine")
	float LateralOffsetMaxCm = 300.f;
};

/** Interpolated racing-line data at an arbitrary arc length. */
USTRUCT()
struct MIDANAI_API FRacingLineSample
{
	GENERATED_BODY()

	FVector WorldLocation = FVector::ZeroVector;
	FVector ForwardDirection = FVector::ForwardVector;

	float ReferenceTargetSpeedKmh = 0.f;
	bool bBrakingZone = false;

	float LateralOffsetMinCm = 0.f;
	float LateralOffsetMaxCm = 0.f;
};
